version: '3.5'
services:
  caddy:
    image: "abiosoft/caddy"
    volumes:
      - ./certificates:/root/.caddy  # to save certificates on disk
      - ./Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "80:80"
      - "443:443"
      - "2015:2015"

    networks:
      - proxynet

networks:
  proxynet:
    name: caddy_proxy_network